// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnWwFnirDcoGq1eNzXarl-4rGWBHoNyCk',
    appId: '1:153077082538:web:52b94345613bf006ffe3d3',
    messagingSenderId: '153077082538',
    projectId: 'wellnow-3b505',
    authDomain: 'wellnow-3b505.firebaseapp.com',
    storageBucket: 'wellnow-3b505.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKH_6FISW86HmiltVFJOQHNyG_aP79lvc',
    appId: '1:153077082538:android:e92ef49a568ce7aeffe3d3',
    messagingSenderId: '153077082538',
    projectId: 'wellnow-3b505',
    storageBucket: 'wellnow-3b505.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiF6adOGa0f01U3-rF50_FxymYmGa78jk',
    appId: '1:153077082538:ios:1f488c0c165c2a6cffe3d3',
    messagingSenderId: '153077082538',
    projectId: 'wellnow-3b505',
    storageBucket: 'wellnow-3b505.appspot.com',
    iosBundleId: 'com.example.wellnow',
  );
}
